db:
  active:
    ipaddress: IP 
  database: databaseName
  port: 5432
  username: userName
  password: password
 
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${db.active.ipaddress}:${db.port}/${db.database}
    username: ${db.username}
    password: ${db.password}
  jpa:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        show_sql: true
      properties.hibernate.temp.use_jdbc_metadata_defaults: false
 

